### PR TITLE
SA-19554 Extend cloudera scm manager start timeout

### PR DESCRIPTION
**Pull request by sotarokimura-dotdata**

### CODE REVIEW

**Comment by sotarokimura-dotdata** [comment]
Firstly I will confirm by this branches code.

**Comment by bzakdd** [comment]
I don't think that it will help. In tests:
https://jenkins.bigdata.9livesdata.com/view/Platform/job/sa_platform_install_with_external_hadoop_secured/70/consoleFull
this command ends instantaneously. When the problem arises it seems that cloudera-scm cannot get up, not that it get's up quickly enough.

**Comment by sotarokimura-dotdata** [comment]
Below result, were 64 seconds passed during wait?
Then I thought waiting time affects result.

```
11:09:59  RUNNING HANDLER [scm : wait cloudera-scm-server] *******************************
11:09:59  task path: /ansible/roles/scm/handlers/main.yml:9
11:11:07  ok: [ec2-34-218-234-17.us-west-2.compute.amazonaws.com] => {"changed": false, "elapsed": 64, "path": null, "port": 7180, "search_regex": null, "state": "started"}
11:11:07  META: ran handlers
```

**Comment by bzakdd** [comment]
Yes, sorry, I made a mistake.
And I see that in AWS message:
```
2019-07-24 04:31:19,094 INFO ScmActive-0:com.cloudera.server.cmf.components.ScmActive: ScmActive completed successfully.
```
comes after a minute delay, so I think you are right.

**Review by takumi-dtdt — APPROVED** [review]

**Pull request merged**
